//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int up=75; // angle for the servo being up
int down=235; // angle for the servo being down
int rotatingangle = 0;
double ratiospeed= 1;
double ratiodistance= 1;
double onedegree = 6350/360;

void moverobot(int speed, int waitms){//positie speed makes robot move forward
	motor[motorFL] = speed;
	motor[motorFR] = speed;
	motor[motorBL] = speed;
	motor[motorBR] = speed;
	wait1Msec(waitms);
}

void moveinches(float distance, int speed=20)

// 1 inch=200ms @ speed 10
// 1 inch= 60mn @ speed=20
// 1 inch = 43mn @ speed = 30
{
int ms_per_inch_10=200;
int ms_per_inch_20=60;
int ms_per_inch_30=43;
int ms_per_inch=0;

switch(speed)
{
	case 10: ms_per_inch=ms_per_inch_10;
  case 20: ms_per_inch=ms_per_inch_20;
  case 30: ms_per_inch=ms_per_inch_30;
}

int waitms=abs(distance)*ms_per_inch;
speed=speed*abs(distance)/distance;
moverobot(speed, waitms);
}

void sliderobot(int speed, int waitms){//positie speed makes robot slide right
	motor[motorFL] = speed;
	motor[motorFR] = -speed;
	motor[motorBL] = -speed;
	motor[motorBR] = speed;
	wait1Msec(waitms);
}
void turnrobot(int speed, int waitms){ //positie speed makes robot slide right
	motor[motorFL] = speed;
	motor[motorFR] = -speed;
	motor[motorBL] = speed;
	motor[motorBR] = -speed;
	wait1Msec(waitms);
}

void turnangle(int angle){ //positie speed makes robot slide right
	int howfast = 10;
	int howlong = 0;
	if(angle<0)
	{
		howfast = -10;
	}

	howlong=onedegree*abs(angle);
	//howfast=-10;
	turnrobot(howfast, howlong);
	//turnrobot(-10, howlong);

}

int timeTraveled=0;
int timeToTravel=2800;
int threshwall=10;
int x=0;
task main(){
//	servo[servo1]=up;
//moverobot(30,500);
	moveinches(10);
//	turnangle(3600);
}
