#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"
//


#pragma DebuggerWindows("nxtLCDScreen")
#pragma DebuggerWindows("joystickGame")



float getspeedleft(int x, int y)
{
float	r=1/sqrt(2);
return(x*r+y*r);
}


float getspeedright(int x, int y)
{
float	r=1/sqrt(2);
return(-x*r+y*r);

}

void debugjoystick()
{
   getJoystickSettings(joystick);
    nxtDisplayTextLine(0, "U:%s/S:%s", joystick.UserMode ? "True" : "False", joystick.StopPgm ? "True" : "False");
    nxtDisplayTextLine(1, "X1:%d / Y1:%d", joystick.joy1_x1, joystick.joy1_y1);
    nxtDisplayTextLine(2, "X2:%d / Y2:%d", joystick.joy1_x2, joystick.joy1_y2);
    nxtDisplayTextLine(3, "Btn:%d / TH:%d", joystick.joy1_Buttons, joystick.joy1_TopHat);
    nxtDisplayTextLine(4, "Counter: %d", nNoMessageCounter);
    nxtDisplayTextLine(5, "X1:%d / Y1:%d", joystick.joy2_x1, joystick.joy2_y1);
    nxtDisplayTextLine(6, "X2:%d / Y2:%d", joystick.joy2_x2, joystick.joy2_y2);
    nxtDisplayTextLine(7, "Btn:%d / TH:%d", joystick.joy2_Buttons, joystick.joy2_TopHat);
    wait1Msec(20);
}

task main()
{
	float fl=10, br=0, fr=0, bl=0;
int x1=0, y1=0, x2=0, y2=0;

  int threshold = 20;             /* Int 'threshold' will allow us to ignore low       */
                                  /* readings that keep our robot in perpetual motion. */
  float reduction_moves=1;
 float reduction_turns=0.25;

  while(true)                            // Infinite loop:
  {

    getJoystickSettings(joystick);
 //   debugjoystick();

    fl=br=fr=bl=0;

   	x1=joystick.joy1_x1/1.28 ;
		y1=joystick.joy1_y1/1.28;

		x2=joystick.joy1_x2/1.28;

    if(abs(x1) > threshold | abs(y1) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
 {

			fl=getspeedleft(x1,y1)*reduction_moves;
			br=fl;
			fr=getspeedright(x1,y1)*reduction_moves;
			bl=fr;


}

   /* if(abs(x2) > threshold&&fl>0) {
   	fl=fl+x2;
		bl=bl+x2;
		fr=fr-x2;
		br=br-x2;*/
   		// If the right analog stick's Y-axis readings are either above or below the threshold:
//}else
	if(abs(x2) > threshold) {
 	fl=fl+x2*reduction_turns;
	bl=bl+x2*reduction_turns;
	fr=fr-x2*reduction_turns;
	br=br-x2*reduction_turns;
}




	nxtDisplayTextLine(1, "L:%d / R:%d", fl, fr);

 motor[motorFL] = fl;
  motor[motorFR] = fr;
	motor[motorBL] = bl;
	motor[motorBR] = br;
	wait1Msec(100);


  }

}
