#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorBL,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorBR,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
//
int down = 0;//degrees for tube clam servo to be down
int up = 90;//degrees for tube clam servo to be up


float HIGH_SPEED = 1; //high speed setting
float LOW_SPEED = .25; //low speed setting
float MAX_SPEED = 1; //starting speed not max

float fl, br, fr, bl;
int x1, y1, x2;

int threshold = 5;          // Int 'threshold' will allow us to ignore low


float reduction_turns=0.25;


float getspeedleft(int x, int y){
	float	r=1/sqrt(2);
	return(x*r+y*r);
}


float getspeedright(int x, int y){
	float	r=1/sqrt(2);
	return(-x*r+y*r);

}



task main(){
	while(true){    // Infinite loop:

		getJoystickSettings(joystick);
		if(joy1Btn(1)==1&&servo[servo1]==down){
			servo[servo1]=up;
			break;
		}
		else if(joy1Btn(1)==1&&servo[servo1]==up){
			servo[servo1]=down;
		}

		fl=br=fr=bl=0;//maybe not needed

		x1=joystick.joy1_x1/1.28 ; //reductions for joysticks
		y1=joystick.joy1_y1/1.28;

		x2=joystick.joy1_x2/1.28;

		if(abs(x1) > threshold | abs(y1) > threshold){   // If the right analog stick's Y-axis readings are either above or below the threshold:
			fl=getspeedleft(x1,y1);
			br=fl;//sets same axis motors to the same value
			fr=getspeedright(x1,y1);
			bl=fr;//sets same axis motors to the same values
		}


		if(abs(x2) > threshold) {
			fl+=x2*reduction_turns;
			bl+=x2*reduction_turns;
			fr-=x2*reduction_turns;
			br-=x2*reduction_turns;
		}

		if(MAX_SPEED==HIGH_SPEED&&joy1Btn(11)==1){
			MAX_SPEED=LOW_SPEED;
			wait10Msec(100);
		}else if(MAX_SPEED==LOW_SPEED&&joy1Btn(11)==1){
			MAX_SPEED=HIGH_SPEED;
		}
	

		/*if(joy1Btn(10)==1){
			pressed=true;           //speed button setings
			}else if(pressed==true){
			if(MAX_SPEED==HIGH_SPEED){
				MAX_SPEED=LOW_SPEED;
				pressed=false;
				}else{
				MAX_SPEED=HIGH_SPEED;
				pressed=false;
			}
		}
*/


		motor[motorBR]= br * MAX_SPEED;
		motor[motorBL]= bl * MAX_SPEED;
		motor[motorFR]= fr * MAX_SPEED;
		motor[motorFL]= fl * MAX_SPEED;

		nxtDisplayTextLine(1, "L:%d / R:%d", fl, fr);
	}
}
