#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int trigger_time_right;//milliseconds right trigger was held down
int trigger_time_left;//millisecond left trigger was held down

int moved_trigger_time_left;
int moved_trigger_time_right;

int targetState;//state to go to on scissor lift
int currentState;//current state on scissor lift

int move;// milliseconds the motor moves

int motorSpeed = 100; //speed of scissor lift motor

int down = 0;//milliseconds to go up to the positon
int low = 1000;
int medium = 2000;
int high = 3000;
int up = 4000; //center goal



void fn_move();


task main(){
	while(true){
		while(joy1Btn(8)==1){//read how long trigger were held down
			wait1Msec(10);
			trigger_time_right+=10;
		}
		while(joy1Btn(7)==1){
			wait1Msec(10);
			trigger_time_left+=10;
		}



		if(joy1Btn(1)==1){ //reads which buttons were pressed and tells which level they go to
			targetState = high;
			}else if(joy1Btn(2)==1){
			targetState = medium;
			}else if(joy1Btn(3)==1){
			targetState = low;
			}else if(joy1Btn(4)==1){
			targetState = up;
			}else if(joy1Btn(5)==1){
			targetState = down;
		}



		//does calculations for both moving and triggers
		if(targetState==currentState){//if scissor lift isnt told to move use trigger times

			if(currentState==down){//if scissor lift is down only move up with trigggers
				move += trigger_time_left;

				}else if (currentState==up){//if scissor lift is up only moe down with triggers
				move -= trigger_time_right;

				}else{
				move += trigger_time_left - trigger_time_right;
			}




			}else if(targetState!=currentState){//if scissor lift is told to move

			if(targetState==down){//if moving all the way down
				move = -currentState;//+trigger_time_left;//only can move up with trigger so doesnt exeed down
				move -= moved_trigger_time_left + moved_trigger_time_right;

				/*	}else if(targetState==up){//REMOVE IF CENTER GOAL HIGHT IS LESS THAN MAX HIGHT
				move=targetState-currentState;//if moving all the way up
				move = move - moved_trigger_time_left + moved_trigger_time_right;
				//	move=move-trigger_time_right;*/

				}else if(targetState>currentState){//if it is going up
				move = targetState-currentState;
				move -= moved_trigger_time_left + moved_trigger_time_right;
				//	move= move + trigger_time_left - trigger_time_right;

				}else if(targetState<currentState){//if it is going down
				move = currentState-targetState;
				move = -move;
				move -= moved_trigger_time_left + moved_trigger_time_right;
			}
		}
	}
}




void fn_move(){
	motor[motorH]=motorSpeed;
	wait1Msec(move);
	motor[motorH]=0;

	if(trigger_time_left!=0&&trigger_time_right!=0){
		moved_trigger_time_left=trigger_time_left;
		moved_trigger_time_right=trigger_time_right;
		trigger_time_left=0;
		trigger_time_right=0;
	}
	move=0;
	currentState=targetState;
}
